// Generated by CoffeeScript 1.6.1
(function() {
  var fs, _;

  fs = require('fs');

  _ = require('underscore');

  module.exports = {
    loadDir: function(dir, pattern, callback) {
      return fs.stat(dir, function(err, stats) {
        var files, filteredFiles, prefix;
        if (err || !stats.isFile() && !stats.isDirectory()) {
          return callback(new Error("File does not exist"), null, dir);
        }
        if (stats.isFile()) {
          files = [dir];
          prefix = '../../';
        } else {
          files = fs.readdirSync(dir);
          prefix = '../../' + dir;
        }
        if (pattern != null) {
          filteredFiles = _.filter(files, function(filename) {
            return (filename.search(pattern)) >= 0;
          });
        } else {
          filteredFiles = files;
        }
        _.each(filteredFiles, function(filename) {
          var fileToLoad, loadedFile;
          fileToLoad = prefix + filename;
          loadedFile = require(fileToLoad);
          if (callback != null) {
            callback(null, loadedFile, fileToLoad.substring(6));
          }
        });
      });
    },
    loadDirs: function(dirs, pattern, callback) {
      var that;
      that = this;
      _.each(dirs, function(dir) {
        that.loadDir(dir, pattern, callback);
      });
    }
  };

}).call(this);
